name: CD

on:
  push:
    branches: [ main ]

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c Release -o output
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Nuget Configure
      run: dotnet nuget add source --username nickmartin1ee7 --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/nickmartin1ee7/index.json"
    - name: Nuget Publish
      run: dotnet nuget push "output/Uwuify.Humanizer.1.0.0.nupkg"  --api-key ${{ secrets.GITHUB_TOKEN }} --source "github"
