name: CI/CD

on:
  workflow_dispatch:  
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
  publish:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c Release -o output
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Nuget Configure
      run: dotnet nuget add source --username nickmartin1ee7 --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/nickmartin1ee7/index.json"
    - name: Nuget Publish - GitHub
      run: dotnet nuget push "output/*.nupkg"  --api-key ${{ secrets.GITHUB_TOKEN }} --source "github"
    - name: Nuget Publish - GitHub
      run: dotnet nuget push "output/*.nupkg"  --api-key ${{ secrets.NUGET_KEY }} --source "https://api.nuget.org/v3/index.json"
