name: CI/CD

on:
  workflow_dispatch:  
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
      
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
  
  publish:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: [ build, test ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c Release -o output
    - name: Publish - win-x64
      run: dotnet publish --no-restore -r win-x64 -c Release -o release-win-x64
    - name: Publish - win-x86
      run: dotnet publish --no-restore -r win-x86 -c Release -o release-win-x86
    - name: Publish - linux-x64
      run: dotnet publish --no-restore -r linux-x64 -c Release -o release-linux-x64
    - name: Publish - osx-x64
      run: dotnet publish --no-restore -r osx-x64 -c Release -o release-osx-x64
    - name: Nuget Configure
      run: dotnet nuget add source --username nickmartin1ee7 --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/nickmartin1ee7/index.json"
    - name: Nuget Publish - GitHub
      run: dotnet nuget push "output/*.nupkg"  --api-key ${{ secrets.GITHUB_TOKEN }} --source "github" --skip-duplicate
    - name: Nuget Publish - NuGet.org
      run: dotnet nuget push "output/*.nupkg"  --api-key ${{ secrets.NUGET_KEY }} --source "https://api.nuget.org/v3/index.json" --skip-duplicate
    - name: GitHub Publish - Archive - win-x64
      run: zip -r release-win-x64.zip release-win-x64
    - name: GitHub Publish - Archive - win-x86
      run: zip -r release-win-x86.zip release-win-x86
    - name: GitHub Publish - Archive - linux-x64
      run: zip -r release-linux-x64.zip release-linux-x64
    - name: GitHub Publish - Archive - osx-x64
      run: zip -r release-osx-x64.zip release-osx-x64
    - name: GitHub Publish - Release
      uses: softprops/action-gh-release@v1      
      with:
        tag_name: ${{ github.workflow }}
        name: Release ${{ github.run_number }}
        draft: false
        prerelease: false
        files: release-*.zip
